### ISSUE TITLE
Cannot add manifests in cluster-network-03-config.yml.j2 

### ISSUE THREAD

**Issue by mtarsel** [ocp-power-automation/ocp4-playbooks#143] opened 2021-12-02 03:36 UTC
IPSec requires OVNKubernetes to be enabled. As a test, I enabled ipsec in `playbooks/roles/ocp-config/templates/cluster-network-03-config.yml.j2` every time `cni_network_provider = OVNKubernetes` was set in local var.tfvars file however this did not work. 

If I would cat to this file via the main.yaml in ocp-config module it would work. I created [a branch on my fork](https://github.com/mtarsel/ocp4-playbooks/tree/ipsec-bug) with 2 commits to demonstrate the issue.

On that branch, here is the commit that will _**NOT**_ enable ipsec: https://github.com/mtarsel/ocp4-playbooks/commit/513b3863899504247d8a361a5b9f0a7dae492b64

Cat to same file from main.yaml will enable ipsec: https://github.com/mtarsel/ocp4-playbooks/commit/679c24766a9b912ca88799db5a3b50dfa1c2cf99

[OpenShift documentation about enabling IPsec here](https://docs.openshift.com/container-platform/4.9/installing/installing_bare_metal/installing-bare-metal-network-customizations.html#modifying-nwoperator-config-startup_installing-bare-metal-network-customizations)

**Comment by aishwaryabk** [comment] 2021-12-13 06:29
The issue is encountered as the file `playbooks/roles/ocp-config/templates/cluster-network-03-config.yml.j2` is not getting copied to the manifests folder as the `cni_network_mtu` variable is not defined in the PowerVM code.

**Comment by aishwaryabk** [comment] 2021-12-14 06:57
Raised a PR on PowerVM: https://github.com/ocp-power-automation/ocp4-upi-powervm/pull/229

**Comment by yussufsh** [comment] 2022-05-05 07:35
This seems fixed by @aishwaryabk

**Closed as completed by yussufsh** 2022-05-05 07:35 UTC
